version: '3.1'
services:
  mysql:
    image: mariadb:10.11
    hostname: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    networks:
      - slurm-network

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    environment:
      SLURM_NUM_NODES: 4
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql
    networks:
      - slurm-network

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    environment:
      SLURM_NUM_NODES: 4
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - ${DATA:-slurm_jobdir}:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
    networks:
      - slurm-network

  worker-1: &worker
    image: slurm-docker-cluster:${IMAGE_TAG}
    command: ["slurmd"]
    container_name: worker-1
    hostname: worker-1
    environment:
      SLURM_NUM_NODES: 4
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - ${DATA:-slurm_jobdir}:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network

  worker-2:
    <<: *worker
    container_name: worker-2
    hostname: worker-2

  worker-3:
    <<: *worker
    container_name: worker-3
    hostname: worker-3

  worker-4:
    <<: *worker
    container_name: worker-4
    hostname: worker-4


volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:

networks:
  slurm-network:
    driver: bridge
